name: Publish Package to npmjs
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: '20.16'
          registry-url: 'https://registry.npmjs.org'
      
      # Install dependencies using npm ci if lockfile exists, otherwise use npm install
      - run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi
      
      - run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
